### ISSUE TITLE
How to use your tool to solve my problem

### ISSUE THREAD

**Issue by kyisoethin** [tintinweb/ecdsa-private-key-recovery#6]
I want to ask for advice in my case of CTF lab.
So, if this is out of question type, you can leave it.
I have signatures that use ruby securerandom and it uses same k nonce.
I know the domain. But I don't know how to get public key.
So, I can have two signatures and their r and s.
Then, how can I substitute these values in your script?
I think I have to replace the following code .
```
sampleA = EcDsaSignature((3791300999159503489677918361931161866594575396347524089635269728181147153565,   #r
                          49278124892733989732191499899232294894006923837369646645433456321810805698952), #s
                         bignum_to_hex(
                             765305792208265383632692154455217324493836948492122104105982244897804317926).decode(
                             "hex"),
                         pub)
```
I know r and s. But I do not know what to replace third argument.
So, please help me to solve my problem.

**Comment by tintinweb** [comment]
Hi @kyisoethin,

the public key is required. It is probably part of your CTF challenge to recover the pubkey from (r,s). [this](https://crypto.stackexchange.com/questions/18105/how-does-recovering-the-public-key-from-an-ecdsa-signature-work) thread could be of help. I am pretty sure there's a tool that will help you where you provide curve, r,s to recover pubkey canditates and then you feed (pubkey, r,s1)(pubkey,r,s2) into ecdsa-private-key-recovery to get the privkey.

cheers,
tin

**Comment by kyisoethin** [comment]
Thanks for your answer. Now I get public keys.
I have code like following.

```
from ecdsa_key_recovery import DsaSignature, EcDsaSignature
import ecdsa
# specify curve
def bignum_to_hex(val, nbits=256):
    ret = hex((val + (1 << nbits)) % (1 << nbits)).rstrip("L").lstrip("0x")
    if len(ret) % 2 == 1:
        # even out hexstr
        return "0" + ret
    return ret
curve = ecdsa.SECP256k1

# create standard ecdsa pubkey object from hex-encoded string
pub = ecdsa.VerifyingKey.from_string(
          "e224b4a6a6c9856ccc6fc1b9b319d12e5a91dd8f82debf8ef855b98ddd999568357768adcd3c4f94a603c4a1a8be51656f43a68b85f5f0967bbb3e6088ecb9e6".decode(
            "hex"), curve=curve).pubkey
            
# create sampleA and sampleB recoverable signature objects.
# long r, long s, bytestr hash, pubkey obj.
sampleA = EcDsaSignature((21505829891763648114329055987619236494102133314575206970830385799158076338148,   #r
                          49278124892733989732191499899232294894006923837369646645433456321810805698952), #s
                         bignum_to_hex(
                             43320816902991540908233314200962897836318887557253939552326052776734928405047).decode(
                             "hex"),
                         pub)
sampleB = EcDsaSignature((21505829891763648114329055987619236494102133314575206970830385799158076338148,   #r
                          53828364483890576541359509152275798410474923026901634481754793139467844213586), #s'
                         bignum_to_hex(
                             113818374509822654475474837557585340239451820549068534289749207735977861114659).decode(
                             "hex"),
                         pub)
                         
# key not yet recovered
assert (sampleA.x is None)
```
But this error occur

```
Traceback (most recent call last):
  File "ecdsa2.py", line 24, in <module>
    pub)
  File "build/bdist.linux-x86_64/egg/ecdsa_key_recovery/__init__.py", line 186, in __init__
AssertionError
```
So, how can I solve this?

**Comment by mikejnpc** [comment]
Hey tin.. is there a utility you recommend to pull R S from a specific candidate .... (already have the pubkey) 
Thanks.

Kind Regards
Mikej
