### ISSUE TITLE
Hello! program error.

### ISSUE THREAD

**Issue by hunaman** [tintinweb/ecdsa-private-key-recovery#8]
python bitcrack.py recover
<module>             -  ########################################
<module>             -  #WARNING: experimental script. no warranty. you've been warned!
<module>             -  ########################################
<module>             -  recover
Traceback (most recent call last):
  File "bitcrack.py", line 769, in <module>
    recover_privkey()
  File "bitcrack.py", line 622, in recover_privkey
    cursor.execute("select id,hex(r) from bitcoin.r_dup where r not in (select r from bitcoin.privkeys) order by RAND()")
  File "/home/guns/.local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/home/guns/.local/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
_mysql_exceptions.OperationalError: (1049, "Unknown database 'bitcoin'")

**Comment by hunaman** [comment]
Import Error
dabfff918a46967ad6f490aca5ffe34df22d4d067fdf649c132d95b8dd4664cb SubstrateUnderrunError('55-octet short',)
bec86abc2bde2e31ea7d185337edd2cb3d7e3277437cb169755118708b1146b7 SubstrateUnderrunError('80-octet short',)
8e1853c35271eb002e2f91656c567858800b7d5c240a778c3f67347b789ed9dc PyAsn1Error('Indefinite length encoding not supported by this codec',)
b97259f795bdf17f7d47bf012ecd2f94ac306efc597821e3afb00684d1e9e262 SubstrateUnderrunError('24-octet short',)
3c6a3ea7c01b233775dd454b29c25d2b5000ec02e66398505f01ce08e2208ce1 SubstrateUnderrunError('96-octet short'
Please help?
